apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Exposed service port
      targetPort: 3003  # Container app listening port
      nodePort: 31003   # Exposed host machine port (range: 30000-32767)
