apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
spec:
  type: NodePort
  selector:
    app: nginx-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000  # Single exposed port
