apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Exposed service port
      targetPort: 3004  # Container app listening port
      nodePort: 31004   # Exposed host machine port (range: 30000-32767)
