apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Exposed service port
      targetPort: 3002  # Container app listening port
      nodePort: 31002   # Exposed host machine port (range: 30000-32767)
