apiVersion: v1
kind: Service
metadata:
  name: restaurants-service
spec:
  selector:
    app: restaurants-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Exposed service port
      targetPort: 3001  # Container app listening port
      nodePort: 31001   # Exposed host machine port (range: 30000-32767)
